// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proxyservice.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Proxyservice_Algorithm: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case drop // = 0
  case proportional // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .drop
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .drop
    case 1: self = .proportional
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .drop: return 0
    case .proportional: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Proxyservice_Algorithm: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Proxyservice_Algorithm] = [
    .drop,
    .proportional,
  ]
}

#endif  // swift(>=4.2)

public enum Proxyservice_Usability: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unusable // = 0
  case barely // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unusable
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unusable
    case 1: self = .barely
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unusable: return 0
    case .barely: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Proxyservice_Usability: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Proxyservice_Usability] = [
    .unusable,
    .barely,
  ]
}

#endif  // swift(>=4.2)

public enum Proxyservice_Mode: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case progressive // = 0
  case focus // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .progressive
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .progressive
    case 1: self = .focus
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .progressive: return 0
    case .focus: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Proxyservice_Mode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Proxyservice_Mode] = [
    .progressive,
    .focus,
  ]
}

#endif  // swift(>=4.2)

public enum Proxyservice_AppType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case instagram // = 0
  case tiktok // = 1
  case twitter // = 2
  case youtube // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .instagram
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .instagram
    case 1: self = .tiktok
    case 2: self = .twitter
    case 3: self = .youtube
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .instagram: return 0
    case .tiktok: return 1
    case .twitter: return 2
    case .youtube: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Proxyservice_AppType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Proxyservice_AppType] = [
    .instagram,
    .tiktok,
    .twitter,
    .youtube,
  ]
}

#endif  // swift(>=4.2)

public struct Proxyservice_Preset {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Behavior mode of the preset.
  /// TODO: switch to oneof
  public var mode: Proxyservice_Mode = .progressive

  /// Base speed in "Focus mode"
  public var baseRxSpeedTarget: Double = 0

  /// Break speed. Use Infinity to indicate no speed capping.
  public var temporaryRxSpeedTarget: Double = 0

  /// When a break should end.
  /// TODO: move to a State message
  public var temporaryRxSpeedExpiry: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _temporaryRxSpeedExpiry ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_temporaryRxSpeedExpiry = newValue}
  }
  /// Returns true if `temporaryRxSpeedExpiry` has been explicitly set.
  public var hasTemporaryRxSpeedExpiry: Bool {return self._temporaryRxSpeedExpiry != nil}
  /// Clears the value of `temporaryRxSpeedExpiry`. Subsequent reads from it will return its default value.
  public mutating func clearTemporaryRxSpeedExpiry() {self._temporaryRxSpeedExpiry = nil}

  /// How fast healing should happen.
  public var usageHealRate: Double = 0

  /// How long a user should be able to scroll.
  public var usageMaxHp: Double = 0

  /// A maximum speed to govern scrolling traffic.
  public var usageBaseRxSpeedTarget: Double = 0

  /// ID of the preset
  public var id: String = String()

  public var trafficRules: Proxyservice_TrafficRules {
    get {return _trafficRules ?? Proxyservice_TrafficRules()}
    set {_trafficRules = newValue}
  }
  /// Returns true if `trafficRules` has been explicitly set.
  public var hasTrafficRules: Bool {return self._trafficRules != nil}
  /// Clears the value of `trafficRules`. Subsequent reads from it will return its default value.
  public mutating func clearTrafficRules() {self._trafficRules = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _temporaryRxSpeedExpiry: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _trafficRules: Proxyservice_TrafficRules? = nil
}

/// Rules for slowing down
public struct Proxyservice_TrafficRules {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// repeated string app_ids = 1;
  public var matchAllTraffic: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proxyservice_Overlay {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var preset: Proxyservice_Preset {
    get {return _preset ?? Proxyservice_Preset()}
    set {_preset = newValue}
  }
  /// Returns true if `preset` has been explicitly set.
  public var hasPreset: Bool {return self._preset != nil}
  /// Clears the value of `preset`. Subsequent reads from it will return its default value.
  public mutating func clearPreset() {self._preset = nil}

  public var expiry: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _expiry ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_expiry = newValue}
  }
  /// Returns true if `expiry` has been explicitly set.
  public var hasExpiry: Bool {return self._expiry != nil}
  /// Clears the value of `expiry`. Subsequent reads from it will return its default value.
  public mutating func clearExpiry() {self._expiry = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _preset: Proxyservice_Preset? = nil
  fileprivate var _expiry: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Proxyservice_Settings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A version used for migrations of this message.
  /// Latest version: 2
  public var version: Int32 {
    get {return _storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var debug: Bool {
    get {return _storage._debug}
    set {_uniqueStorage()._debug = newValue}
  }

  /// Parameters of the active preset.
  public var defaultPreset: Proxyservice_Preset {
    get {return _storage._defaultPreset ?? Proxyservice_Preset()}
    set {_uniqueStorage()._defaultPreset = newValue}
  }
  /// Returns true if `defaultPreset` has been explicitly set.
  public var hasDefaultPreset: Bool {return _storage._defaultPreset != nil}
  /// Clears the value of `defaultPreset`. Subsequent reads from it will return its default value.
  public mutating func clearDefaultPreset() {_uniqueStorage()._defaultPreset = nil}

  /// Overlay preset
  public var overlay: Proxyservice_Overlay {
    get {return _storage._overlay ?? Proxyservice_Overlay()}
    set {_uniqueStorage()._overlay = newValue}
  }
  /// Returns true if `overlay` has been explicitly set.
  public var hasOverlay: Bool {return _storage._overlay != nil}
  /// Clears the value of `overlay`. Subsequent reads from it will return its default value.
  public mutating func clearOverlay() {_uniqueStorage()._overlay = nil}

  /// NOT used by the backend:
  /// TODO: move these to a preferences proto.
  public var parachutePreset: Proxyservice_Preset {
    get {return _storage._parachutePreset ?? Proxyservice_Preset()}
    set {_uniqueStorage()._parachutePreset = newValue}
  }
  /// Returns true if `parachutePreset` has been explicitly set.
  public var hasParachutePreset: Bool {return _storage._parachutePreset != nil}
  /// Clears the value of `parachutePreset`. Subsequent reads from it will return its default value.
  public mutating func clearParachutePreset() {_uniqueStorage()._parachutePreset = nil}

  /// Tracks the last change to the settings.
  public var changeMetadata: Proxyservice_ChangeMetadata {
    get {return _storage._changeMetadata ?? Proxyservice_ChangeMetadata()}
    set {_uniqueStorage()._changeMetadata = newValue}
  }
  /// Returns true if `changeMetadata` has been explicitly set.
  public var hasChangeMetadata: Bool {return _storage._changeMetadata != nil}
  /// Clears the value of `changeMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearChangeMetadata() {_uniqueStorage()._changeMetadata = nil}

  /// Set of apps
  public var apps: Dictionary<Int32,Bool> {
    get {return _storage._apps}
    set {_uniqueStorage()._apps = newValue}
  }

  /// NOT used by the backend:
  /// TODO: move these to a preferences proto.
  public var quickSessionSecs: Int32 {
    get {return _storage._quickSessionSecs}
    set {_uniqueStorage()._quickSessionSecs = newValue}
  }

  public var longSessionSecs: Int32 {
    get {return _storage._longSessionSecs}
    set {_uniqueStorage()._longSessionSecs = newValue}
  }

  public var algorithm: Proxyservice_Algorithm {
    get {return _storage._algorithm}
    set {_uniqueStorage()._algorithm = newValue}
  }

  public var usability: Proxyservice_Usability {
    get {return _storage._usability}
    set {_uniqueStorage()._usability = newValue}
  }

  /// Disable temporarily. Meant as a last resort option.
  public var disabledUntil: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._disabledUntil ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._disabledUntil = newValue}
  }
  /// Returns true if `disabledUntil` has been explicitly set.
  public var hasDisabledUntil: Bool {return _storage._disabledUntil != nil}
  /// Clears the value of `disabledUntil`. Subsequent reads from it will return its default value.
  public mutating func clearDisabledUntil() {_uniqueStorage()._disabledUntil = nil}

  public var userID: String {
    get {return _storage._userID}
    set {_uniqueStorage()._userID = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Proxyservice_ChangeMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var reason: String = String()

  public var timestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _timestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  public var hasTimestamp: Bool {return self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimestamp() {self._timestamp = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _timestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Proxyservice_Request {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var message: Proxyservice_Request.OneOf_Message? = nil

  public var setSettings: Proxyservice_Settings {
    get {
      if case .setSettings(let v)? = message {return v}
      return Proxyservice_Settings()
    }
    set {message = .setSettings(newValue)}
  }

  public var getState: Proxyservice_GetStateRequest {
    get {
      if case .getState(let v)? = message {return v}
      return Proxyservice_GetStateRequest()
    }
    set {message = .getState(newValue)}
  }

  public var heal: Proxyservice_HealRequest {
    get {
      if case .heal(let v)? = message {return v}
      return Proxyservice_HealRequest()
    }
    set {message = .heal(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Message: Equatable {
    case setSettings(Proxyservice_Settings)
    case getState(Proxyservice_GetStateRequest)
    case heal(Proxyservice_HealRequest)

  #if !swift(>=4.1)
    public static func ==(lhs: Proxyservice_Request.OneOf_Message, rhs: Proxyservice_Request.OneOf_Message) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.setSettings, .setSettings): return {
        guard case .setSettings(let l) = lhs, case .setSettings(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.getState, .getState): return {
        guard case .getState(let l) = lhs, case .getState(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.heal, .heal): return {
        guard case .heal(let l) = lhs, case .heal(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

public struct Proxyservice_SetSettingsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proxyservice_GetStateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proxyservice_GetStateResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var usagePoints: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proxyservice_HealRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proxyservice_HealResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var usagePoints: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Proxyservice_Algorithm: @unchecked Sendable {}
extension Proxyservice_Usability: @unchecked Sendable {}
extension Proxyservice_Mode: @unchecked Sendable {}
extension Proxyservice_AppType: @unchecked Sendable {}
extension Proxyservice_Preset: @unchecked Sendable {}
extension Proxyservice_TrafficRules: @unchecked Sendable {}
extension Proxyservice_Overlay: @unchecked Sendable {}
extension Proxyservice_Settings: @unchecked Sendable {}
extension Proxyservice_ChangeMetadata: @unchecked Sendable {}
extension Proxyservice_Request: @unchecked Sendable {}
extension Proxyservice_Request.OneOf_Message: @unchecked Sendable {}
extension Proxyservice_SetSettingsResponse: @unchecked Sendable {}
extension Proxyservice_GetStateRequest: @unchecked Sendable {}
extension Proxyservice_GetStateResponse: @unchecked Sendable {}
extension Proxyservice_HealRequest: @unchecked Sendable {}
extension Proxyservice_HealResponse: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proxyservice"

extension Proxyservice_Algorithm: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "drop"),
    1: .same(proto: "proportional"),
  ]
}

extension Proxyservice_Usability: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "unusable"),
    1: .same(proto: "barely"),
  ]
}

extension Proxyservice_Mode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PROGRESSIVE"),
    1: .same(proto: "FOCUS"),
  ]
}

extension Proxyservice_AppType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "instagram"),
    1: .same(proto: "tiktok"),
    2: .same(proto: "twitter"),
    3: .same(proto: "youtube"),
  ]
}

extension Proxyservice_Preset: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Preset"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "mode"),
    3: .same(proto: "baseRxSpeedTarget"),
    4: .same(proto: "temporaryRxSpeedTarget"),
    5: .same(proto: "temporaryRxSpeedExpiry"),
    6: .same(proto: "usageHealRate"),
    7: .same(proto: "usageMaxHP"),
    8: .same(proto: "usageBaseRxSpeedTarget"),
    10: .same(proto: "id"),
    11: .standard(proto: "traffic_rules"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.baseRxSpeedTarget) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.temporaryRxSpeedTarget) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._temporaryRxSpeedExpiry) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.usageHealRate) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.usageMaxHp) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.usageBaseRxSpeedTarget) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._trafficRules) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.mode != .progressive {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 2)
    }
    if self.baseRxSpeedTarget != 0 {
      try visitor.visitSingularDoubleField(value: self.baseRxSpeedTarget, fieldNumber: 3)
    }
    if self.temporaryRxSpeedTarget != 0 {
      try visitor.visitSingularDoubleField(value: self.temporaryRxSpeedTarget, fieldNumber: 4)
    }
    try { if let v = self._temporaryRxSpeedExpiry {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.usageHealRate != 0 {
      try visitor.visitSingularDoubleField(value: self.usageHealRate, fieldNumber: 6)
    }
    if self.usageMaxHp != 0 {
      try visitor.visitSingularDoubleField(value: self.usageMaxHp, fieldNumber: 7)
    }
    if self.usageBaseRxSpeedTarget != 0 {
      try visitor.visitSingularDoubleField(value: self.usageBaseRxSpeedTarget, fieldNumber: 8)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 10)
    }
    try { if let v = self._trafficRules {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_Preset, rhs: Proxyservice_Preset) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.baseRxSpeedTarget != rhs.baseRxSpeedTarget {return false}
    if lhs.temporaryRxSpeedTarget != rhs.temporaryRxSpeedTarget {return false}
    if lhs._temporaryRxSpeedExpiry != rhs._temporaryRxSpeedExpiry {return false}
    if lhs.usageHealRate != rhs.usageHealRate {return false}
    if lhs.usageMaxHp != rhs.usageMaxHp {return false}
    if lhs.usageBaseRxSpeedTarget != rhs.usageBaseRxSpeedTarget {return false}
    if lhs.id != rhs.id {return false}
    if lhs._trafficRules != rhs._trafficRules {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_TrafficRules: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TrafficRules"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "match_all_traffic"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.matchAllTraffic) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.matchAllTraffic != false {
      try visitor.visitSingularBoolField(value: self.matchAllTraffic, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_TrafficRules, rhs: Proxyservice_TrafficRules) -> Bool {
    if lhs.matchAllTraffic != rhs.matchAllTraffic {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_Overlay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Overlay"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "preset"),
    2: .same(proto: "expiry"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._preset) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._expiry) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._preset {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._expiry {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_Overlay, rhs: Proxyservice_Overlay) -> Bool {
    if lhs._preset != rhs._preset {return false}
    if lhs._expiry != rhs._expiry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_Settings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Settings"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    4: .same(proto: "version"),
    7: .same(proto: "debug"),
    11: .same(proto: "defaultPreset"),
    12: .same(proto: "overlay"),
    14: .standard(proto: "parachute_preset"),
    15: .standard(proto: "change_metadata"),
    16: .same(proto: "apps"),
    17: .standard(proto: "quick_session_secs"),
    18: .standard(proto: "long_session_secs"),
    19: .same(proto: "algorithm"),
    20: .same(proto: "usability"),
    21: .standard(proto: "disabled_until"),
    22: .standard(proto: "user_id"),
  ]

  fileprivate class _StorageClass {
    var _version: Int32 = 0
    var _debug: Bool = false
    var _defaultPreset: Proxyservice_Preset? = nil
    var _overlay: Proxyservice_Overlay? = nil
    var _parachutePreset: Proxyservice_Preset? = nil
    var _changeMetadata: Proxyservice_ChangeMetadata? = nil
    var _apps: Dictionary<Int32,Bool> = [:]
    var _quickSessionSecs: Int32 = 0
    var _longSessionSecs: Int32 = 0
    var _algorithm: Proxyservice_Algorithm = .drop
    var _usability: Proxyservice_Usability = .unusable
    var _disabledUntil: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _userID: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _debug = source._debug
      _defaultPreset = source._defaultPreset
      _overlay = source._overlay
      _parachutePreset = source._parachutePreset
      _changeMetadata = source._changeMetadata
      _apps = source._apps
      _quickSessionSecs = source._quickSessionSecs
      _longSessionSecs = source._longSessionSecs
      _algorithm = source._algorithm
      _usability = source._usability
      _disabledUntil = source._disabledUntil
      _userID = source._userID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._version) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._debug) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._defaultPreset) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._overlay) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._parachutePreset) }()
        case 15: try { try decoder.decodeSingularMessageField(value: &_storage._changeMetadata) }()
        case 16: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufBool>.self, value: &_storage._apps) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._quickSessionSecs) }()
        case 18: try { try decoder.decodeSingularInt32Field(value: &_storage._longSessionSecs) }()
        case 19: try { try decoder.decodeSingularEnumField(value: &_storage._algorithm) }()
        case 20: try { try decoder.decodeSingularEnumField(value: &_storage._usability) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._disabledUntil) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._userID) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._version != 0 {
        try visitor.visitSingularInt32Field(value: _storage._version, fieldNumber: 4)
      }
      if _storage._debug != false {
        try visitor.visitSingularBoolField(value: _storage._debug, fieldNumber: 7)
      }
      try { if let v = _storage._defaultPreset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._overlay {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._parachutePreset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._changeMetadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      } }()
      if !_storage._apps.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufBool>.self, value: _storage._apps, fieldNumber: 16)
      }
      if _storage._quickSessionSecs != 0 {
        try visitor.visitSingularInt32Field(value: _storage._quickSessionSecs, fieldNumber: 17)
      }
      if _storage._longSessionSecs != 0 {
        try visitor.visitSingularInt32Field(value: _storage._longSessionSecs, fieldNumber: 18)
      }
      if _storage._algorithm != .drop {
        try visitor.visitSingularEnumField(value: _storage._algorithm, fieldNumber: 19)
      }
      if _storage._usability != .unusable {
        try visitor.visitSingularEnumField(value: _storage._usability, fieldNumber: 20)
      }
      try { if let v = _storage._disabledUntil {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
      if !_storage._userID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userID, fieldNumber: 22)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_Settings, rhs: Proxyservice_Settings) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._debug != rhs_storage._debug {return false}
        if _storage._defaultPreset != rhs_storage._defaultPreset {return false}
        if _storage._overlay != rhs_storage._overlay {return false}
        if _storage._parachutePreset != rhs_storage._parachutePreset {return false}
        if _storage._changeMetadata != rhs_storage._changeMetadata {return false}
        if _storage._apps != rhs_storage._apps {return false}
        if _storage._quickSessionSecs != rhs_storage._quickSessionSecs {return false}
        if _storage._longSessionSecs != rhs_storage._longSessionSecs {return false}
        if _storage._algorithm != rhs_storage._algorithm {return false}
        if _storage._usability != rhs_storage._usability {return false}
        if _storage._disabledUntil != rhs_storage._disabledUntil {return false}
        if _storage._userID != rhs_storage._userID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_ChangeMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChangeMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "reason"),
    3: .same(proto: "timestamp"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._timestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 2)
    }
    try { if let v = self._timestamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_ChangeMetadata, rhs: Proxyservice_ChangeMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Request"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "setSettings"),
    2: .same(proto: "getState"),
    3: .same(proto: "heal"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Proxyservice_Settings?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .setSettings(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .setSettings(v)
        }
      }()
      case 2: try {
        var v: Proxyservice_GetStateRequest?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .getState(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .getState(v)
        }
      }()
      case 3: try {
        var v: Proxyservice_HealRequest?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .heal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .heal(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .setSettings?: try {
      guard case .setSettings(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getState?: try {
      guard case .getState(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .heal?: try {
      guard case .heal(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_Request, rhs: Proxyservice_Request) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_SetSettingsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetSettingsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_SetSettingsResponse, rhs: Proxyservice_SetSettingsResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_GetStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetStateRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_GetStateRequest, rhs: Proxyservice_GetStateRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_GetStateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetStateResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "usagePoints"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.usagePoints) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.usagePoints != 0 {
      try visitor.visitSingularDoubleField(value: self.usagePoints, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_GetStateResponse, rhs: Proxyservice_GetStateResponse) -> Bool {
    if lhs.usagePoints != rhs.usagePoints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_HealRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_HealRequest, rhs: Proxyservice_HealRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proxyservice_HealResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "usagePoints"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.usagePoints) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.usagePoints != 0 {
      try visitor.visitSingularDoubleField(value: self.usagePoints, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proxyservice_HealResponse, rhs: Proxyservice_HealResponse) -> Bool {
    if lhs.usagePoints != rhs.usagePoints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
