// Objective-C API for talking to strange.industries/go-proxy/pkg/ffi Go package.
//   gobind -lang=objc strange.industries/go-proxy/pkg/ffi
//
// File is generated by gobind. Do not edit.

#ifndef __Ffi_H__
#define __Ffi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FfiMobileLogger;
@class FfiOnDeviceProxyBridge;
@protocol FfiProxyBridge;
@class FfiProxyBridge;

@protocol FfiProxyBridge <NSObject>
- (void)close;
- (NSData* _Nullable)rpc:(NSData* _Nullable)input error:(NSError* _Nullable* _Nullable)error;
- (void)startProxy:(long)port settingsData:(NSData* _Nullable)settingsData;
@end

@interface FfiMobileLogger : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

@interface FfiOnDeviceProxyBridge : NSObject <goSeqRefInterface, FfiProxyBridge> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field OnDeviceProxyBridge.Proxy with unsupported type: *strange.industries/go-proxy/pkg/proxy.Proxy

// skipped method OnDeviceProxyBridge.AppUsed with unsupported parameter or return types

- (void)beforeSettingsChange;
- (void)close;
// skipped method OnDeviceProxyBridge.DebugGetEntries with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.DebugRecordState with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.GetDefiniteAppMatch with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.GetFlow with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.GetFuzzyAppMatch with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.GetState with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.OnSettingsChange with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.PublishSample with unsupported parameter or return types

- (void)recordIp:(NSString* _Nullable)ip;
// skipped method OnDeviceProxyBridge.RecordState with unsupported parameter or return types

- (void)registerDnsEntry:(NSString* _Nullable)ip name:(NSString* _Nullable)name;
- (void)registerIp:(NSString* _Nullable)ip;
- (NSData* _Nullable)rpc:(NSData* _Nullable)input error:(NSError* _Nullable* _Nullable)error;
- (double)rxSpeedTarget;
// skipped method OnDeviceProxyBridge.SetSettings with unsupported parameter or return types

// skipped method OnDeviceProxyBridge.Start with unsupported parameter or return types

- (void)startProxy:(long)port settingsData:(NSData* _Nullable)settingsData;
// skipped method OnDeviceProxyBridge.UpdateUsagePoints with unsupported parameter or return types

@end

FOUNDATION_EXPORT id<FfiProxyBridge> _Nullable FfiInit(NSString* _Nullable env);

FOUNDATION_EXPORT id<FfiProxyBridge> _Nullable FfiInitDebug(NSString* _Nullable env, NSString* _Nullable debugServerAddr);

FOUNDATION_EXPORT void FfiInitSentry(NSString* _Nullable env);

FOUNDATION_EXPORT long FfiMaxProcs(long max);

FOUNDATION_EXPORT long FfiSetGCPercent(long pct);

FOUNDATION_EXPORT int64_t FfiSetMemoryLimit(int64_t limit);

@class FfiProxyBridge;

@interface FfiProxyBridge : NSObject <goSeqRefInterface, FfiProxyBridge> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)close;
- (NSData* _Nullable)rpc:(NSData* _Nullable)input error:(NSError* _Nullable* _Nullable)error;
- (void)startProxy:(long)port settingsData:(NSData* _Nullable)settingsData;
@end

#endif
