// Code generated by mockery v2.16.0. DO NOT EDIT.

package controller

import mock "github.com/stretchr/testify/mock"

// MockDeviceCallbacks is an autogenerated mock type for the DeviceCallbacks type
type MockDeviceCallbacks struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: title, message
func (_m *MockDeviceCallbacks) SendNotification(title string, message string) {
	_m.Called(title, message)
}

type mockConstructorTestingTNewMockDeviceCallbacks interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDeviceCallbacks creates a new instance of MockDeviceCallbacks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDeviceCallbacks(t mockConstructorTestingTNewMockDeviceCallbacks) *MockDeviceCallbacks {
	mock := &MockDeviceCallbacks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
