
// Objective-C API for talking to the following Go packages
//
//	strange.industries/go-proxy/pkg/ffi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ffi_FRAMEWORK_H__
#define __Ffi_FRAMEWORK_H__

#include "Ffi.objc.h"
#include "Universe.objc.h"

#endif
