// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: proxyservice.proto

package proxyservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRxSpeedTarget   float64 `protobuf:"fixed64,1,opt,name=baseRxSpeedTarget,proto3" json:"baseRxSpeedTarget,omitempty"`
	UseExponentialDecay bool    `protobuf:"varint,2,opt,name=useExponentialDecay,proto3" json:"useExponentialDecay,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proxyservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proxyservice_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetBaseRxSpeedTarget() float64 {
	if x != nil {
		return x.BaseRxSpeedTarget
	}
	return 0
}

func (x *Settings) GetUseExponentialDecay() bool {
	if x != nil {
		return x.UseExponentialDecay
	}
	return false
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Request_SetSettings
	//	*Request_SetTemporaryRxSpeedTarget
	//	*Request_ResetPoints
	Message isRequest_Message `protobuf_oneof:"message"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proxyservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proxyservice_proto_rawDescGZIP(), []int{1}
}

func (m *Request) GetMessage() isRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Request) GetSetSettings() *Settings {
	if x, ok := x.GetMessage().(*Request_SetSettings); ok {
		return x.SetSettings
	}
	return nil
}

func (x *Request) GetSetTemporaryRxSpeedTarget() *SetTemporaryRxSpeedTargetRequest {
	if x, ok := x.GetMessage().(*Request_SetTemporaryRxSpeedTarget); ok {
		return x.SetTemporaryRxSpeedTarget
	}
	return nil
}

func (x *Request) GetResetPoints() *ResetPointsRequest {
	if x, ok := x.GetMessage().(*Request_ResetPoints); ok {
		return x.ResetPoints
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_SetSettings struct {
	SetSettings *Settings `protobuf:"bytes,1,opt,name=setSettings,proto3,oneof"`
}

type Request_SetTemporaryRxSpeedTarget struct {
	SetTemporaryRxSpeedTarget *SetTemporaryRxSpeedTargetRequest `protobuf:"bytes,2,opt,name=setTemporaryRxSpeedTarget,proto3,oneof"`
}

type Request_ResetPoints struct {
	ResetPoints *ResetPointsRequest `protobuf:"bytes,3,opt,name=resetPoints,proto3,oneof"`
}

func (*Request_SetSettings) isRequest_Message() {}

func (*Request_SetTemporaryRxSpeedTarget) isRequest_Message() {}

func (*Request_ResetPoints) isRequest_Message() {}

type ResetPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetPointsRequest) Reset() {
	*x = ResetPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPointsRequest) ProtoMessage() {}

func (x *ResetPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxyservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPointsRequest.ProtoReflect.Descriptor instead.
func (*ResetPointsRequest) Descriptor() ([]byte, []int) {
	return file_proxyservice_proto_rawDescGZIP(), []int{2}
}

type SetTemporaryRxSpeedTargetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed    float64 `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Duration int32   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *SetTemporaryRxSpeedTargetRequest) Reset() {
	*x = SetTemporaryRxSpeedTargetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTemporaryRxSpeedTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTemporaryRxSpeedTargetRequest) ProtoMessage() {}

func (x *SetTemporaryRxSpeedTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxyservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTemporaryRxSpeedTargetRequest.ProtoReflect.Descriptor instead.
func (*SetTemporaryRxSpeedTargetRequest) Descriptor() ([]byte, []int) {
	return file_proxyservice_proto_rawDescGZIP(), []int{3}
}

func (x *SetTemporaryRxSpeedTargetRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SetTemporaryRxSpeedTargetRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rxBytes,proto3" json:"rxBytes,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // how long the sample
	Points        float64                `protobuf:"fixed64,5,opt,name=points,proto3" json:"points,omitempty"`
	K             float64                `protobuf:"fixed64,6,opt,name=k,proto3" json:"k,omitempty"`
	MinutesLeft   float64                `protobuf:"fixed64,7,opt,name=minutesLeft,proto3" json:"minutesLeft,omitempty"`
	RxSpeed       float64                `protobuf:"fixed64,8,opt,name=rxSpeed,proto3" json:"rxSpeed,omitempty"`
	RxSpeedTarget float64                `protobuf:"fixed64,9,opt,name=rxSpeedTarget,proto3" json:"rxSpeedTarget,omitempty"`
	Matches       []string               `protobuf:"bytes,10,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxyservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proxyservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proxyservice_proto_rawDescGZIP(), []int{4}
}

func (x *Sample) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Sample) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *Sample) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Sample) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Sample) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Sample) GetK() float64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *Sample) GetMinutesLeft() float64 {
	if x != nil {
		return x.MinutesLeft
	}
	return 0
}

func (x *Sample) GetRxSpeed() float64 {
	if x != nil {
		return x.RxSpeed
	}
	return 0
}

func (x *Sample) GetRxSpeedTarget() float64 {
	if x != nil {
		return x.RxSpeedTarget
	}
	return 0
}

func (x *Sample) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_proxyservice_proto protoreflect.FileDescriptor

var file_proxyservice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x2c, 0x0a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x52, 0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x30, 0x0a,
	0x13, 0x75, 0x73, 0x65, 0x45, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x44,
	0x65, 0x63, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x75, 0x73, 0x65, 0x45,
	0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x63, 0x61, 0x79, 0x22,
	0x86, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x73,
	0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x6e, 0x0a, 0x19, 0x73, 0x65, 0x74, 0x54, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x52, 0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6d,
	0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x52, 0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x19, 0x73, 0x65,
	0x74, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x52, 0x78, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x44, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54,
	0x0a, 0x20, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x52, 0x78,
	0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xaa, 0x02, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73,
	0x4c, 0x65, 0x66, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x75,
	0x74, 0x65, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x78, 0x53, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x72, 0x78, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x78, 0x53, 0x70, 0x65, 0x65, 0x64, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x72, 0x78, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proxyservice_proto_rawDescOnce sync.Once
	file_proxyservice_proto_rawDescData = file_proxyservice_proto_rawDesc
)

func file_proxyservice_proto_rawDescGZIP() []byte {
	file_proxyservice_proto_rawDescOnce.Do(func() {
		file_proxyservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxyservice_proto_rawDescData)
	})
	return file_proxyservice_proto_rawDescData
}

var file_proxyservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proxyservice_proto_goTypes = []interface{}{
	(*Settings)(nil),                         // 0: proxyservice.Settings
	(*Request)(nil),                          // 1: proxyservice.Request
	(*ResetPointsRequest)(nil),               // 2: proxyservice.ResetPointsRequest
	(*SetTemporaryRxSpeedTargetRequest)(nil), // 3: proxyservice.SetTemporaryRxSpeedTargetRequest
	(*Sample)(nil),                           // 4: proxyservice.Sample
	(*timestamppb.Timestamp)(nil),            // 5: google.protobuf.Timestamp
}
var file_proxyservice_proto_depIdxs = []int32{
	0, // 0: proxyservice.Request.setSettings:type_name -> proxyservice.Settings
	3, // 1: proxyservice.Request.setTemporaryRxSpeedTarget:type_name -> proxyservice.SetTemporaryRxSpeedTargetRequest
	2, // 2: proxyservice.Request.resetPoints:type_name -> proxyservice.ResetPointsRequest
	5, // 3: proxyservice.Sample.startTime:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proxyservice_proto_init() }
func file_proxyservice_proto_init() {
	if File_proxyservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxyservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTemporaryRxSpeedTargetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxyservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proxyservice_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Request_SetSettings)(nil),
		(*Request_SetTemporaryRxSpeedTarget)(nil),
		(*Request_ResetPoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxyservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxyservice_proto_goTypes,
		DependencyIndexes: file_proxyservice_proto_depIdxs,
		MessageInfos:      file_proxyservice_proto_msgTypes,
	}.Build()
	File_proxyservice_proto = out.File
	file_proxyservice_proto_rawDesc = nil
	file_proxyservice_proto_goTypes = nil
	file_proxyservice_proto_depIdxs = nil
}
